#### Numpy array using randint

In [ ]:
import numpy as np
electricity=np.random.randint(120,650,size=(4,7))
print(electricity)
print(electricity.shape)
print(electricity.size)




[[403 184 560 249 379 139 421]
 [156 417 394 568 368 125 521]
 [350 183 414 144 234 489 371]
 [463 389 241 420 191 128 305]]
(4, 7)
28


#### Average usuage per hostel,maximum usuage per hostel and highest average usuage 

In [6]:
average_usuageperhostel=electricity.mean(axis=1)
print(average_usuageperhostel)

max_usuage=electricity.max(axis=1)
print(max_usuage)

highest_average_index=np.argmax(average_usuageperhostel)
print(highest_average_index)

[333.57142857 364.14285714 312.14285714 305.28571429]
[560 568 489 463]
1


#### Total Electricity Consumption

In [7]:
total_consumption=electricity.sum()
print(total_consumption)

9206


#### Broadcasting 

In [9]:
new_electricity=np.where(electricity>550,electricity*1.20,electricity).astype(int)
print(new_electricity)

[[403 184 672 249 379 139 421]
 [156 417 394 681 368 125 521]
 [350 183 414 144 234 489 371]
 [463 389 241 420 191 128 305]]


#### Comparing average hostel consumption to daily consumption

In [15]:
compare_consumption = np.where(
    electricity > average_usuageperhostel[:, None],
    True,
    False
)

print(compare_consumption)


[[ True False  True False  True False  True]
 [False  True  True  True  True False  True]
 [ True False  True False False  True  True]
 [ True  True False  True False False False]]


#### Reshaping

In [17]:
print(electricity.reshape(1,28))
print(electricity.reshape(2,14))

[[403 184 560 249 379 139 421 156 417 394 568 368 125 521 350 183 414 144
  234 489 371 463 389 241 420 191 128 305]]
[[403 184 560 249 379 139 421 156 417 394 568 368 125 521]
 [350 183 414 144 234 489 371 463 389 241 420 191 128 305]]


#### Copy vs View

In [18]:
ref_backup=electricity
safe_backup=electricity.copy()
electricity[2][3]=222
print(ref_backup)
print(safe_backup)


[[403 184 560 249 379 139 421]
 [156 417 394 568 368 125 521]
 [350 183 414 222 234 489 371]
 [463 389 241 420 191 128 305]]
[[403 184 560 249 379 139 421]
 [156 417 394 568 368 125 521]
 [350 183 414 144 234 489 371]
 [463 389 241 420 191 128 305]]
