In [ ]:
import numpy as np
marks=np.array([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]])


[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


#### Total Elements,Size and Data Type

In [22]:
print(marks.size)
print(marks)
print(marks.dtype)
print(marks.shape)

15
[[69 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
int64
(5, 3)


#### Data Indexing and Slicing

In [12]:
print(marks[1][:])
print(marks[:,2])

[45 60 55]
[90 55 95 35 75]


#### Mean and Average

In [14]:
print(np.mean(marks,axis=1))
print(np.mean(marks,axis=0))

[84.33333333 53.33333333 91.66666667 35.         70.        ]
[61.2 69.4 70. ]


#### Filtering Top Performers

In [15]:
avg_per_student = np.mean(marks, axis=1)

# students with average >= 80
result = marks[avg_per_student >= 80]
print(result)


[[78 85 90]
 [88 92 95]]


#### Pass/fail

In [16]:
result = np.where(marks >= 50, "Pass", "Fail")
print(result)

[['Pass' 'Pass' 'Pass']
 ['Fail' 'Pass' 'Pass']
 ['Pass' 'Pass' 'Pass']
 ['Fail' 'Fail' 'Fail']
 ['Pass' 'Pass' 'Pass']]


#### Data Cleaning

In [17]:
updated_marks = np.where(marks < 40, 0, marks)
print(updated_marks)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [ 0 40  0]
 [65 70 75]]


#### Nested Condition


In [18]:
avg = np.mean(marks, axis=1)

grades = np.where(avg >= 85, "A",
         np.where(avg >= 70, "B",
         np.where(avg >= 50, "C", "No Grade")))

scores = np.where(avg >= 85, 10,
         np.where(avg >= 70, 8,
         np.where(avg >= 50, 6, 0)))

print("Average:", avg)
print("Grade:", grades)
print("Score:", scores)

Average: [84.33333333 53.33333333 91.66666667 35.         70.        ]
Grade: ['B' 'C' 'A' 'No Grade' 'B']
Score: [ 8  6 10  0  8]


#### .copy vs =

In [21]:
backup=marks
backup[0,0]=69
print(backup)
print(marks)

backup2=marks.copy()
backup2[0][0]=6969696996
print(backup2)
print(marks)

[[69 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[69 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
[[6969696996         85         90]
 [        45         60         55]
 [        88         92         95]
 [        30         40         35]
 [        65         70         75]]
[[69 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
