In [1]:
import numpy as np


In [2]:
arr=np.array([1,2,3,4,5])

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
arr_CostPrice=np.array([1500,3000,5000,8000])
arr_daily_sales=np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])
print(arr_CostPrice)
print(arr_daily_sales)

[1500 3000 5000 8000]
[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]


In [5]:
print(arr_daily_sales+2)

[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]


In [6]:
print(np.dot(arr_daily_sales,arr_CostPrice))

[196000  96500  54000]


In [10]:
print(np.sqrt(arr_daily_sales))

[[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]


In [ ]:
print(arr_daily_sales[1])

[10 15  8 12]


In [21]:
first_2_days = arr_daily_sales[:2, :]
print(first_2_days)


[[10 15  8 12]
 [ 5  7  4  6]]


In [22]:
print(arr_daily_sales[2][2])

2


In [23]:
print(arr_daily_sales.reshape(12))

[10 15  8 12  5  7  4  6  2  3  2  4]


In [24]:
print(arr_daily_sales.reshape(2,6))

[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]


In [26]:
print(np.linspace(0,100,10))

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
